[variables]
    NIXPACKS_PHP_VARIANT = "8.2"

[phases.setup]
    nixPkgs = ["php82", "php82Packages.composer", "nginx"]

[phases.install]
    cmds = ["composer install --ignore-platform-reqs"]

[start]
    cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"